### PR TITLE
Add ard functions for tables 11 & 12

### LINKED ISSUE #242: [New ARD]: Table 11 & 12
See https://github.com/pharmaverse/cardinal/issues/101 and https://pharmaverse.github.io/cardinal/quarto/table-templates/template-table_11.html

### PR DESCRIPTION
**Pull request by edelarua**
# Pull Request

Closes #242

### CODE REVIEW

**Comment by edelarua** [comment]
@ayogasekaram what are your thoughts on this layout for the quarto template pages?

**Comment by ayogasekaram** [comment]
@edelarua I like that it's been simplified! Less info to parse through too. Do we still need the rtables option? Since it can't accommodate ARDs - it might be a bit out of place now

**Comment by edelarua** [comment]
> @edelarua I like that it's been simplified! Less info to parse through too. Do we still need the rtables option? Since it can't accommodate ARDs - it might be a bit out of place now

I think we should keep the rtables stuff for now until we decide to remove it from the package altogether. Since most functions are still only creating rtables we can keep them for reference and once everything is converted maybe remove it all at once. What do you think?

Keep in mind we'll also need to make updates in a bunch of other places at some point with an explanation of the new direction of the package.

**Comment by aassuied-ps** [comment]
Hi @edelarua,
It seems great! I have one question though. What will happen if you have a different subset to get from `df` and `denominator`?

I see this:

```
  df <- preproc_df_table_11(df, id_var, arm_var, saffl_var, fmqsc_var, fmqnam_var, fmq_scope, na_level)

  if (is.null(denominator)) {
    denominator <- df # nocov
  } else {
    denominator <- alt_counts_df_preproc(denominator, id_var, arm_var, saffl_var)
  }
```
So I guess you should have the same condition for both datasets (`saffl_var`). In some cases on adverse events tables we need to filter on more than just the safety analysis flag (take primary SOC only for instances).
Should we consider the pre-processing work on selecting rows should be only about analysis population and the user does the rest before running the function?

**Review by ayogasekaram — APPROVED** [review]
looks good to me! thanks @edelarua

**Pull request merged**
